POST /auth/register
Host: localhost:8080
Content-Type: application/json

{
  "email":"davinda@mail.com",
  "password":"yuhu"
}

###

POST /auth/register
Host: localhost:8080
Content-Type: application/json

{
  "email":"naldy@mail.com",
  "password":"yuhu"
}

###

POST /auth/login
Host: localhost:8080
Content-Type: application/json

{
  "email":"davinda@mail.com",
  "password":"yuhu"
}

###

DELETE /users/10
Host: localhost:8080

###

GET /users?search=x
Host: localhost:8080

###
GET /users/1
Host: localhost:8080

###
PATCH /users/1
Host: localhost:8080
Content-Type: application/json

{
  "email":"yuhu@mail.com"
}